### ISSUE TITLE
Timezone file permissions

### ISSUE THREAD

**Issue by olessavluk** [M4nu/ansible#3]
In this commit - https://github.com/M4nu/ansible/commit/951ed4c7afcf88ae51869bfe5c0af88331e9688b
@EmmanuelVella why have you set `mode=600` for `timezone` and `localtime` files? (default mode is `644`)
This will make them unreadable to other users and work only for root user.

**Comment by EmmanuelVella** [comment]
Hello @olessavluk, thank you for reporting this, that's indeed a mistake. It's fixed in https://github.com/M4nu/ansible/commit/bb9c96319694950ea239bad03e8ac41b2d0dad39
